{
  "path": "/documentation/cfnetwork/cfnetworkerrors/cfsocks4erroridentdfailed",
  "type": "Enumeration Case",
  "name": "CFNetworkErrors.cfsocks4ErrorIdentdFailed",
  "desc": "The server couldnâ€™t connect to the identd daemon on the client and rejected the request.",
  "items": [],
  "declaration": "case cfsocks4ErrorIdentdFailed = 111"
}