{
  "path": "/documentation/appstoreserverapi/generalinternalretryableerror",
  "type": "Object",
  "name": "GeneralInternalRetryableError",
  "desc": "An error response that indicates an unknown error occurred; to try again, resend the same request.",
  "items": [
    {
      "name": "errorCode"
    },
    {
      "name": "errorMessage"
    }
  ]
}