{
  "path": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/err",
  "type": "Enumeration Case",
  "name": "CFNetDiagnosticStatusValues.err",
  "desc": "An error occurred that prevented the call from completing.",
  "items": [],
  "declaration": "case err = -66560"
}