{
  "path": "/documentation/cfnetwork/cfnetworkerrors/cfsocks5errorbadcredentials",
  "type": "Enumeration Case",
  "name": "CFNetworkErrors.cfsocks5ErrorBadCredentials",
  "desc": "The SOCKS server refused the client connection because of bad login credentials.",
  "items": [],
  "declaration": "case cfsocks5ErrorBadCredentials = 122"
}