{
  "path": "/documentation/foundation/nsexceptionname/1412959-destinationinvalidexception",
  "type": "Type Property",
  "name": "destinationInvalidException",
  "desc": "Name of an exception that occurs when an internal assertion fails and implies an unexpected condition within the distributed objects.",
  "items": [],
  "declaration": "static let destinationInvalidException: NSExceptionName"
}